spring:
  cloud:
    stream:
      function:
        definition: orderSupplier; paymentEventConsumer
      bindings:
        orderSupplier-out-0: order-event
        paymentEventConsumer-in-0: payment-event
server:
  port: 8081