apiVersion: apps/v1
kind: Deployment
metadata:
  name: combined-service         # Name of the deployment
  labels:
    app: combined-service
spec:
  replicas: 1                     # Number of desired pods
  selector:
    matchLabels:
      app: combined-service                # Must match pod template labels
  template:
    metadata:
      labels:
        app: combined-service               # Labels for the pod
    spec:
      containers:
        - name: book-service    # Name of the container
          image: book-service:1.0       # Replace with your image
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: log-volume
              mountPath: /logs
          ports:
            - containerPort: 8080       # Port exposed by the container
        - name: logging-service    # Name of the container
          image: logging-service:1.0       # Replace with your image
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: log-volume
              mountPath: /logs
          ports:
            - containerPort: 8081       # Port exposed by the container
      volumes:
        - name: log-volume
          emptyDir: {}