tickets:
  events:
    url: http://localhost:8081
management:
  endpoints:
    web:
      exposure:
        include: health,env,beans,conditions,mappings,loggers
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
